### ISSUE TITLE
Add more CSS rules

### ISSUE THREAD

**Issue by vog** [UNC-Libraries/jquery.xmleditor#73]
Some aspects of the `jquery.xmleditor` CSS styling rely on being applied on top of `reset.css`, which might have simplified things, but has two disadvantages when integrating `jquery.xmleditor` into an existing website:

1. The website might not want to have e.g. lists without bullets, but can't simply enable them globally without affecting the `jquery.xmleditor` widget.
2. Some CSS frameworks might not work properly in combination with `reset.css`.

I propose to add the following rules (or similar rules) to `css/jquery.xmleditor.css`. These will make no difference when `reset.css` is used, but will be of great help when integrating `jquery.xmleditor` into an existing website.

```css
.xml_editor_container ul {
    list-style: none;
}
.xml_editor_container .xml_menu_bar ul {
    padding: 0;
}
.xml_editor_container .xml_menu_column ul {
    padding: 0;
}
.xml_editor_container ul.element_header {
    box-sizing: content-box;
}
.xml_editor_container a {
    color: inherit;
    text-decoration: none;
}
```

The larger goal might be to add a few more rules to make `jquery.xmleditor` independent of any surrounding CSS framework, be it `reset.css` or otherwise. But even without that goal in mind, the above rules would already be a huge improvement of the current situation.

@bbpennel What do you think?
